# Example Meshpipe configuration.
# Adjust values to match your environment before deploying.

name: Meshpipe
database_file: /data/meshtastic_history.db
mqtt_broker_address: mqtt.example.com
mqtt_port: 1883
mqtt_username: ""
mqtt_password: ""
mqtt_topic_prefix: msh
mqtt_topic_suffix: /+/+/+/#
default_channel_key: ""
log_level: INFO
capture_store_raw: true
wal_autocheckpoint_pages: 1000
journal_size_limit_bytes: 67108864
sqlite_cache_kib: 8192
sqlite_disable_mmap: true
observability_address: ":2112"
maintenance_interval_minutes: 360
max_envelope_bytes: 262144
grpc_enabled: false
grpc_listen_address: ":7443"
grpc_auth_token: ""
grpc_max_page_size: 500
