name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Go fmt check
        run: |
          fmt_out=$(gofmt -l ./)
          if [ -n "$fmt_out" ]; then
            echo "Files need gofmt:" && echo "$fmt_out" && exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Go test
        run: go test ./...

      - name: Build CLI
        run: go build ./cmd/malla-capture
